### PR TITLE
Custom backend

### PR DESCRIPTION
**Pull request by moriartyjk**
I have added a 'users' collection that can store the data of individual users once they have signed up. When a user has created an account for the first time, they are assigned a user id which can be stored in the firestore database as the document id in the 'users' collection. The user id should stay consistent each time a user logs in. Using this new collection, I have added part of the customization back end. In the customization menu, a cuisine option can be selected and it will be sent to the users profile under the 'preferences' field. The code for the button list is not the most efficient but it works. If we have time, we can make it more streamline. I still need to implement the ability to have these preferences affect the recommendation, but that shouldn't be too difficult. We will probably have to create the ability to clear the preferences as well. 

https://user-images.githubusercontent.com/68746158/163699961-3b4593c4-b96f-4790-a8e0-8529c7bd5d3c.mp4

### CODE REVIEW

**Comment by thcopeland** [comment]
Looks great Jen! If you have time, maybe one improvement would be to store the preferences in an array? But either way, looks good

**Review by thcopeland — APPROVED** [review]

**Comment by SubstormCodes** [comment]
I like it Jennifer!!

**Comment by SubstormCodes** [comment]
I think it looks good Jennifer!

**Comment by moriartyjk** [comment]
Alright, I going to merge this pull request but I will update the storage type for the preferences and update the UI.

**Pull request merged**
